application: gophervids
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static/(.*\.(css|png))$
  static_files: static/\1
  upload: static/.*\.(css|png)$

- url: /.*
  script: _go_app
